const SUPABASE_URL='https://evmqqjtglapwnezbttds.supabase.co';
const SUPABASE_KEY='sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w';
let db=null;try{if(window.supabase?.createClient)db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY)}catch(e){console.warn(e)}
let data={buys:[],home:[],recipes:[],plan:[],budget:0,reminders:[]};
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n)||0);
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2200)}
function show(screen){const target=$('#'+screen);if(!target)return;$$('.screen').forEach(x=>x.classList.remove('active'));target.classList.add('active');window.scrollTo(0,0);if(screen==='recetas')renderRecipes(window.currentCategory||'desayuno');if(screen==='recordatorios')renderReminders();if(window.innerWidth<=900){const n=$('#nav');if(n)n.style.display='none'}}
function esc(s){return String(s??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function bindNavigation(){document.addEventListener('click',e=>{const btn=e.target.closest('[data-screen]');if(!btn)return;e.preventDefault();window.currentCategory=btn.dataset.cat||window.currentCategory||'desayuno';show(btn.dataset.screen);if(btn.dataset.cat&&btn.dataset.screen==='recetas')renderRecipes(btn.dataset.cat)});$$('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{window.currentCategory=btn.dataset.cat;show('recetas');renderRecipes(btn.dataset.cat)}));const menu=$('#hamb');if(menu)menu.addEventListener('click',()=>{const n=$('#nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.flexDirection='column';n.style.position='absolute';n.style.top='76px';n.style.right='10px';n.style.background='#fff';n.style.padding='10px';n.style.borderRadius='16px';n.style.boxShadow='0 12px 30px #6c405d18'})}
async function init(){bindNavigation();if(!db){renderAll();return}await Promise.all([loadBuys(),loadHome(),loadRecipes(),loadBudget(),loadPlan(),loadReminders()]);renderAll()}
async function loadBuys(){const {data:d,error}=await db.from('shopping_items').select('*').order('created_at',{ascending:false});if(error)toast(error.message);else data.buys=d||[]}
async function loadHome(){const {data:d,error}=await db.from('home_ingredients').select('*').order('created_at',{ascending:false});if(error)toast(error.message);else data.home=d||[]}
async function loadRecipes(){const {data:d,error}=await db.from('recipes').select('*,recipe_ingredients(*)').order('created_at');if(error)toast(error.message);else data.recipes=d||[]}
async function loadBudget(){const {data:d,error}=await db.from('budget').select('*').eq('id',1).maybeSingle();if(error)toast(error.message);else data.budget=Number(d?.weekly_budget)||0}
async function loadPlan(){const {data:d,error}=await db.from('weekly_planner').select('*,recipes(name,category)').order('day_of_week');if(error)toast(error.message);else data.plan=d||[]}
async function loadReminders(){const {data:d,error}=await db.from('reminders').select('*').order('completed').order('reminder_date',{ascending:true}).order('reminder_time',{ascending:true});if(error)toast('Recordatorios: '+error.message);else data.reminders=d||[]}
function renderAll(){renderBuys();renderHome();renderRecipes(window.currentCategory||'desayuno');renderPlanner();renderBudget();renderReminders();stats()}
function stats(){const spent=data.buys.filter(x=>x.purchased).reduce((a,x)=>a+Number(x.estimated_price||0),0);if($('#sBuy'))$('#sBuy').textContent=data.buys.filter(x=>!x.purchased).length;if($('#sHome'))$('#sHome').textContent=data.home.length;if($('#sRec'))$('#sRec').textContent=data.recipes.length;if($('#sSpend'))$('#sSpend').textContent=money(spent)}
function renderBuys(){const e=$('#buyList');if(!e)return;const b=data.buys.filter(x=>!x.purchased);e.innerHTML=b.length?b.map(x=>`<div class="item"><div><b>${esc(x.name)}</b><small>${esc(x.quantity||'')} · ${money(x.estimated_price)}</small></div><button type="button" onclick="buyDone('${x.id}')">✓ Comprado</button></div>`).join(''):'<div class="empty">Tu lista está vacía ♡</div>';if($('#budgetList'))$('#budgetList').innerHTML=data.buys.filter(x=>!x.purchased).map(x=>`<div class="item"><div><b>${esc(x.name)}</b><small>${esc(x.quantity||'')}</small></div><b>${money(x.estimated_price)}</b></div>`).join('')||'<div class="empty">No hay compras pendientes.</div>'}
function renderHome(){const e=$('#homeList');if(!e)return;e.innerHTML=data.home.length?data.home.map(x=>`<article><h3>🏡 ${esc(x.name)}</h3><p>${esc(x.quantity||'Sin cantidad')}</p><button type="button" class="secondary" onclick="delHome('${x.id}')">Eliminar</button></article>`).join(''):'<div class="empty">Todavía no agregaste ingredientes.</div>'}
function renderRecipes(cat){window.currentCategory=cat;$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));const e=$('#recipes');if(!e)return;const r=data.recipes.filter(x=>x.category===cat);e.innerHTML=r.length?r.map(recipeCard).join(''):'<div class="empty">Aún no hay recetas de esta categoría.</div>'}
function recipeCard(r){const have=new Set(data.home.map(x=>x.name.toLowerCase().trim()));const ing=r.recipe_ingredients||[];const missing=ing.filter(i=>!have.has(i.ingredient_name.toLowerCase().trim()));return `<article><h3>🍽️ ${esc(r.name)}</h3><p><b>Ingredientes</b></p><ul>${ing.map(i=>`<li>${esc(i.ingredient_name)}${i.quantity?' · '+esc(i.quantity):''}</li>`).join('')}</ul><p><b>Preparación</b><br>${esc(r.preparation)}</p><p><b>Los tienes:</b> ${ing.filter(i=>have.has(i.ingredient_name.toLowerCase().trim())).map(i=>esc(i.ingredient_name)).join(', ')||'ninguno'}</p><p class="missing"><b>Te faltan:</b> ${missing.map(i=>esc(i.ingredient_name)).join(', ')||'¡nada! 🎉'}</p></article>`}
function renderPlanner(){const e=$('#planner');if(!e)return;const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'],types=['desayuno','almuerzo','merienda','cena'];e.innerHTML=days.map((d,i)=>`<div class="day"><h3>${d}</h3>${types.map(t=>{const p=data.plan.find(x=>x.day_of_week===i+1&&x.meal_type===t);return `<div class="meal" onclick="chooseMeal(${i+1},'${t}')"><small>${t}</small><b>${p?.recipes?.name||'＋ Elegir'}</b></div>`}).join('')}</div>`).join('')}
function renderBudget(){const spent=data.buys.filter(x=>x.purchased).reduce((a,x)=>a+Number(x.estimated_price||0),0),avail=Math.max(0,data.budget-spent),pct=data.budget?Math.min(100,spent/data.budget*100):0;if($('#budgetTotal'))$('#budgetTotal').textContent=money(data.budget);if($('#spent'))$('#spent').textContent=money(spent);if($('#available'))$('#available').textContent=money(avail);if($('#bar'))$('#bar').style.width=pct+'%'}
function renderReminders(){const e=$('#reminderList');if(!e)return;const list=data.reminders||[];e.innerHTML=list.length?list.map(r=>`<div class="item"><div><b>${r.completed?'✓ ':''}${esc(r.title)}</b><small>${esc(r.notes||'')}${r.reminder_date?' · '+r.reminder_date:''}${r.reminder_time?' · '+r.reminder_time.slice(0,5):''}</small></div><button type="button" onclick="toggleReminder('${r.id}',${!r.completed})">${r.completed?'↩ Pendiente':'✓ Hecho'}</button></div>`).join(''):'<div class="empty">Todavía no tienes recordatorios. 🌸</div>'}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}window.closeModal=closeModal;
async function saveBuy(){if(!db)return toast('Supabase no está disponible');const name=$('#fName').value.trim();if(!name)return toast('Escribe un producto');const {data:d,error}=await db.from('shopping_items').insert({name,quantity:$('#fQty').value.trim(),estimated_price:Number($('#fPrice').value)||0}).select().single();if(error)return toast(error.message);data.buys.unshift(d);closeModal();renderAll();toast('Agregado ♡')};window.saveBuy=saveBuy;
async function buyDone(id){if(!db)return;const {error}=await db.from('shopping_items').update({purchased:true}).eq('id',id);if(error)return toast(error.message);const x=data.buys.find(x=>x.id===id);if(x)x.purchased=true;renderAll();toast('Marcado como comprado ✓')};window.buyDone=buyDone;
async function saveHome(){if(!db)return toast('Supabase no está disponible');const name=$('#hName').value.trim();if(!name)return toast('Escribe un ingrediente');const {data:d,error}=await db.from('home_ingredients').insert({name,quantity:$('#hQty').value.trim()}).select().single();if(error)return toast(error.message);data.home.unshift(d);closeModal();renderAll();toast('Ingrediente guardado ♡')};window.saveHome=saveHome;
async function delHome(id){if(!db)return;const {error}=await db.from('home_ingredients').delete().eq('id',id);if(error)return toast(error.message);data.home=data.home.filter(x=>x.id!==id);renderAll()};window.delHome=delHome;
async function saveBudget(){if(!db)return toast('Supabase no está disponible');const weekly_budget=Number($('#bValue').value)||0;const {error}=await db.from('budget').upsert({id:1,weekly_budget,updated_at:new Date().toISOString()});if(error)return toast(error.message);data.budget=weekly_budget;closeModal();renderAll();toast('Presupuesto actualizado 💗')};window.saveBudget=saveBudget;
function chooseMeal(day,type){const opts=data.recipes.filter(r=>r.category===type);if(!opts.length)return toast('Aún no hay recetas de '+type);modal(`<h2>${type} · día ${day}</h2><div class="field"><label>ELIGE UNA RECETA</label><select id="pRecipe">${opts.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></div><button type="button" class="primary full" onclick="saveMeal(${day},'${type}')">Guardar</button>`)}window.chooseMeal=chooseMeal;
async function saveMeal(day,type){if(!db)return toast('Supabase no está disponible');const recipe_id=$('#pRecipe').value;const now=new Date();const diff=(now.getDay()+6)%7;now.setDate(now.getDate()-diff);const week_start=now.toISOString().slice(0,10);const {data:d,error}=await db.from('weekly_planner').upsert({day_of_week:day,meal_type:type,recipe_id,week_start},{onConflict:'week_start,day_of_week,meal_type'}).select('*,recipes(name,category)').single();if(error)return toast(error.message);data.plan=data.plan.filter(x=>!(x.day_of_week===day&&x.meal_type===type&&x.week_start===week_start));data.plan.push(d);closeModal();renderPlanner();toast('Plan guardado 📅')};window.saveMeal=saveMeal;
function openBuy(){modal(`<h2>Agregar a compras 🛒</h2><div class="field"><label>PRODUCTO</label><input id="fName" placeholder="Ej. arroz"></div><div class="field"><label>CANTIDAD</label><input id="fQty" placeholder="Ej. 1 kg"></div><div class="field"><label>PRECIO ESTIMADO</label><input id="fPrice" type="number" min="0" placeholder="0"></div><button type="button" class="primary full" onclick="saveBuy()">Guardar</button>`)}
function openHome(){modal(`<h2>Agregar ingrediente 🏡</h2><div class="field"><label>INGREDIENTE</label><input id="hName" placeholder="Ej. tomate"></div><div class="field"><label>CANTIDAD</label><input id="hQty" placeholder="Ej. 4 unidades"></div><button type="button" class="primary full" onclick="saveHome()">Guardar</button>`)}
function openBudget(){modal(`<h2>Presupuesto semanal 💗</h2><div class="field"><label>PRESUPUESTO</label><input id="bValue" type="number" min="0" value="${data.budget}"></div><button type="button" class="primary full" onclick="saveBudget()">Guardar</button>`)}
function openReminder(){modal(`<h2>Nuevo recordatorio 🔔</h2><div class="field"><label>RECORDATORIO</label><input id="rTitle" placeholder="Ej. Comprar agua"></div><div class="field"><label>NOTA (opcional)</label><input id="rNotes" placeholder="Ej. Antes de las 18:00"></div><div class="field"><label>FECHA</label><input id="rDate" type="date"></div><div class="field"><label>HORA</label><input id="rTime" type="time"></div><button type="button" class="primary full" onclick="saveReminder()">Guardar recordatorio</button>`)}
async function saveReminder(){if(!db)return toast('Supabase no está disponible');const title=$('#rTitle').value.trim();if(!title)return toast('Escribe un recordatorio');const {data:d,error}=await db.from('reminders').insert({title,notes:$('#rNotes').value.trim()||null,reminder_date:$('#rDate').value||null,reminder_time:$('#rTime').value||null}).select().single();if(error)return toast(error.message);data.reminders.push(d);data.reminders.sort((a,b)=>(a.reminder_date||'9999').localeCompare(b.reminder_date||'9999'));closeModal();renderReminders();toast('Recordatorio guardado 🌸')};window.saveReminder=saveReminder;
async function toggleReminder(id,completed){if(!db)return;const {error}=await db.from('reminders').update({completed}).eq('id',id);if(error)return toast(error.message);const r=data.reminders.find(x=>x.id===id);if(r)r.completed=completed;renderReminders()};window.toggleReminder=toggleReminder;
function combos(){const have=new Set(data.home.map(x=>x.name.toLowerCase().trim()));const matches=data.recipes.map(r=>({...r,n:(r.recipe_ingredients||[]).filter(i=>!have.has(i.ingredient_name.toLowerCase().trim())).length})).sort((a,b)=>a.n-b.n).slice(0,6);$('#combo').innerHTML=matches.map(r=>`<article><h3>${esc(r.name)}</h3><p>${r.n===0?'✨ Puedes prepararlo con lo que tienes.':'Te faltan '+r.n+' ingrediente(s).'}</p></article>`).join('')||'<div class="empty">Carga recetas para ver combinaciones.</div>'}
document.addEventListener('DOMContentLoaded',()=>{const addBuy=$('#addBuy'),addHome=$('#addHome'),editBudget=$('#editBudget'),comb=$('#combos'),addReminder=$('#addReminder');if(addBuy)addBuy.onclick=openBuy;if(addHome)addHome.onclick=openHome;if(editBudget)editBudget.onclick=openBudget;if(comb)comb.onclick=combos;if(addReminder)addReminder.onclick=openReminder;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};init()});