const SUPABASE_URL='https://evmqqjtglapwnezbttds.supabase.co';
const SUPABASE_KEY='sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w';
let db=null;
let data={buys:[],home:[],recipes:[],plan:[],budget:0,reminders:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n)||0);
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display='none',2200)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(id){const el=$('#'+id);if(!el)return;$$('.screen').forEach(x=>x.classList.remove('active'));el.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='recetas')renderRecipes(window.currentCategory||'desayuno');if(id==='recordatorios')renderReminders();closeMobileMenu()}
function closeMobileMenu(){if(window.innerWidth<=900){const n=$('#nav');if(n)n.style.display='none'}}
function bindNavigation(){document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(!b)return;e.preventDefault();if(b.dataset.cat)window.currentCategory=b.dataset.cat;show(b.dataset.screen)});document.addEventListener('click',e=>{const b=e.target.closest('.tabs button[data-cat]');if(!b)return;window.currentCategory=b.dataset.cat;show('recetas');renderRecipes(b.dataset.cat)});const h=$('#hamb');if(h)h.addEventListener('click',()=>{const n=$('#nav');if(!n)return;n.style.display=n.style.display==='flex'?'none':'flex';n.style.flexDirection='column';n.style.position='absolute';n.style.top='76px';n.style.right='10px';n.style.background='#fff';n.style.padding='10px';n.style.borderRadius='16px';n.style.boxShadow='0 12px 30px #6c405d18'})}
async function init(){bindNavigation();try{if(window.supabase?.createClient)db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY)}catch(e){console.warn(e)}if(!db){renderAll();return}await Promise.allSettled([loadBuys(),loadHome(),loadRecipes(),loadBudget(),loadPlan(),loadReminders()]);renderAll()}
async function loadBuys(){const r=await db.from('shopping_items').select('*').order('created_at',{ascending:false});if(!r.error)data.buys=r.data||[]}
async function loadHome(){const r=await db.from('home_ingredients').select('*').order('created_at',{ascending:false});if(!r.error)data.home=r.data||[]}
async function loadRecipes(){const r=await db.from('recipes').select('*,recipe_ingredients(*)').order('created_at');if(!r.error)data.recipes=r.data||[]}
async function loadBudget(){const r=await db.from('budget').select('*').eq('id',1).maybeSingle();if(!r.error)data.budget=Number(r.data?.weekly_budget)||0}
async function loadPlan(){const r=await db.from('weekly_planner').select('*,recipes(name,category)').order('day_of_week');if(!r.error)data.plan=r.data||[]}
async function loadReminders(){const r=await db.from('reminders').select('*').order('completed').order('reminder_date',{ascending:true});if(!r.error)data.reminders=r.data||[]}
function renderAll(){renderBuys();renderHome();renderRecipes(window.currentCategory||'desayuno');renderPlanner();renderBudget();renderReminders();stats()}
function stats(){const spent=data.buys.filter(x=>x.purchased).reduce((a,x)=>a+Number(x.estimated_price||0),0);if($('#sBuy'))$('#sBuy').textContent=data.buys.filter(x=>!x.purchased).length;if($('#sHome'))$('#sHome').textContent=data.home.length;if($('#sRec'))$('#sRec').textContent=data.recipes.length;if($('#sSpend'))$('#sSpend').textContent=money(spent)}
function renderBuys(){const e=$('#buyList');if(!e)return;const list=data.buys.filter(x=>!x.purchased);e.innerHTML=list.length?list.map(x=>`<div class="item"><div><b>${esc(x.name)}</b><small>${esc(x.quantity||'')} · ${money(x.estimated_price)}</small></div><button type="button" onclick="buyDone('${x.id}')">✓ Comprado</button></div>`).join(''):'<div class="empty">Tu lista está vacía ♡</div>';if($('#budgetList'))$('#budgetList').innerHTML=list.map(x=>`<div class="item"><div><b>${esc(x.name)}</b><small>${esc(x.quantity||'')}</small></div><b>${money(x.estimated_price)}</b></div>`).join('')||'<div class="empty">No hay compras pendientes.</div>'}
function renderHome(){const e=$('#homeList');if(!e)return;e.innerHTML=data.home.length?data.home.map(x=>`<article><h3>🏡 ${esc(x.name)}</h3><p>${esc(x.quantity||'Sin cantidad')}</p><button type="button" class="secondary" onclick="delHome('${x.id}')">Eliminar</button></article>`).join(''):'<div class="empty">Todavía no agregaste ingredientes.</div>'}
function renderRecipes(cat){window.currentCategory=cat;$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));const e=$('#recipes');if(!e)return;const list=data.recipes.filter(x=>x.category===cat);e.innerHTML=list.length?list.map(recipeCard).join(''):'<div class="empty">Aún no hay recetas de esta categoría.</div>'}
function recipeCard(r){const have=new Set(data.home.map(x=>x.name.toLowerCase().trim()));const ing=r.recipe_ingredients||[];const missing=ing.filter(i=>!have.has(i.ingredient_name.toLowerCase().trim()));return `<article><h3>🍽️ ${esc(r.name)}</h3><p><b>Ingredientes</b></p><ul>${ing.map(i=>`<li>${esc(i.ingredient_name)}${i.quantity?' · '+esc(i.quantity):''}</li>`).join('')}</ul><p><b>Preparación</b><br>${esc(r.preparation)}</p><p><b>Los tienes:</b> ${ing.filter(i=>have.has(i.ingredient_name.toLowerCase().trim())).map(i=>esc(i.ingredient_name)).join(', ')||'ninguno'}</p><p class="missing"><b>Te faltan:</b> ${missing.map(i=>esc(i.ingredient_name)).join(', ')||'¡nada! 🎉'}</p></article>`}
function renderPlanner(){const e=$('#planner');if(!e)return;const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'],types=['desayuno','almuerzo','merienda','cena'];e.innerHTML=days.map((d,i)=>`<div class="day"><h3>${d}</h3>${types.map(t=>{const p=data.plan.find(x=>x.day_of_week===i+1&&x.meal_type===t);return `<div class="meal" onclick="chooseMeal(${i+1},'${t}')"><small>${t}</small><b>${p?.recipes?.name||'＋ Elegir'}</b></div>`}).join('')}</div>`).join('')}
function renderBudget(){const spent=data.buys.filter(x=>x.purchased).reduce((a,x)=>a+Number(x.estimated_price||0),0),available=Math.max(0,data.budget-spent),pct=data.budget?Math.min(100,spent/data.budget*100):0;if($('#budgetTotal'))$('#budgetTotal').textContent=money(data.budget);if($('#spent'))$('#spent').textContent=money(spent);if($('#available'))$('#available').textContent=money(available);if($('#bar'))$('#bar').style.width=pct+'%'}
function renderReminders(){const e=$('#reminderList');if(!e)return;const list=data.reminders||[];e.innerHTML=list.length?list.map(r=>`<div class="item"><div><b>${r.completed?'✓ ':''}${esc(r.title)}</b><small>${esc(r.notes||'')}${r.reminder_date?' · '+r.reminder_date:''}${r.reminder_time?' · '+r.reminder_time.slice(0,5):''}</small></div><button type="button" onclick="toggleReminder('${r.id}',${!r.completed})">${r.completed?'↩ Pendiente':'✓ Hecho'}</button></div>`).join(''):'<div class="empty">Todavía no tienes recordatorios. 🌸</div>'}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('show')}
function closeModal(){$('#modal')?.classList.remove('show')};window.closeModal=closeModal;
async function saveBuy(){if(!db)return toast('Supabase no está disponible');const name=$('#fName').value.trim();if(!name)return toast('Escribe un producto');const r=await db.from('shopping_items').insert({name,quantity:$('#fQty').value.trim(),estimated_price:Number($('#fPrice').value)||0}).select().single();if(r.error)return toast(r.error.message);data.buys.unshift(r.data);closeModal();renderAll();toast('Agregado ♡')};window.saveBuy=saveBuy;
async function buyDone(id){if(!db)return;const r=await db.from('shopping_items').update({purchased:true}).eq('id',id);if(r.error)return toast(r.error.message);const x=data.buys.find(x=>x.id===id);if(x)x.purchased=true;renderAll();toast('Marcado como comprado ✓')};window.buyDone=buyDone;
async function saveHome(){if(!db)return toast('Supabase no está disponible');const name=$('#hName').value.trim();if(!name)return toast('Escribe un ingrediente');const r=await db.from('home_ingredients').insert({name,quantity:$('#hQty').value.trim()}).select().single();if(r.error)return toast(r.error.message);data.home.unshift(r.data);closeModal();renderAll();toast('Ingrediente guardado ♡')};window.saveHome=saveHome;
async function delHome(id){if(!db)return;const r=await db.from('home_ingredients').delete().eq('id',id);if(r.error)return toast(r.error.message);data.home=data.home.filter(x=>x.id!==id);renderAll()};window.delHome=delHome;
async function saveBudget(){if(!db)return toast('Supabase no está disponible');const value=Number($('#bValue').value)||0;const r=await db.from('budget').upsert({id:1,weekly_budget:value,updated_at:new Date().toISOString()});if(r.error)return toast(r.error.message);data.budget=value;closeModal();renderAll();toast('Presupuesto actualizado 💗')};window.saveBudget=saveBudget;
function chooseMeal(day,type){const opts=data.recipes.filter(r=>r.category===type);if(!opts.length)return toast('Aún no hay recetas de '+type);modal(`<h2>${type} · día ${day}</h2><div class="field"><label>ELIGE UNA RECETA</label><select id="pRecipe">${opts.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></div><button type="button" class="primary full" onclick="saveMeal(${day},'${type}')">Guardar</button>`)}window.chooseMeal=chooseMeal;
async function saveMeal(day,type){if(!db)return toast('Supabase no está disponible');const recipe_id=$('#pRecipe').value;const now=new Date();const diff=(now.getDay()+6)%7;now.setDate(now.getDate()-diff);const week_start=now.toISOString().slice(0,10);const r=await db.from('weekly_planner').upsert({day_of_week:day,meal_type:type,recipe_id,week_start},{onConflict:'week_start,day_of_week,meal_type'}).select('*,recipes(name,category)').single();if(r.error)return toast(r.error.message);data.plan=data.plan.filter(x=>!(x.day_of_week===day&&x.meal_type===type&&x.week_start===week_start));data.plan.push(r.data);closeModal();renderPlanner();toast('Plan guardado 📅')};window.saveMeal=saveMeal;
function openBuy(){modal(`<h2>Agregar a compras 🛒</h2><div class="field"><label>PRODUCTO</label><input id="fName" placeholder="Ej. arroz"></div><div class="field"><label>CANTIDAD</label><input id="fQty" placeholder="Ej. 1 kg"></div><div class="field"><label>PRECIO ESTIMADO</label><input id="fPrice" type="number" min="0" placeholder="0"></div><button type="button" class="primary full" onclick="saveBuy()">Guardar</button>`)}
function openHome(){modal(`<h2>Agregar ingrediente 🏡</h2><div class="field"><label>INGREDIENTE</label><input id="hName" placeholder="Ej. tomate"></div><div class="field"><label>CANTIDAD</label><input id="hQty" placeholder="Ej. 4 unidades"></div><button type="button" class="primary full" onclick="saveHome()">Guardar</button>`)}
function openBudget(){modal(`<h2>Presupuesto semanal 💗</h2><div class="field"><label>PRESUPUESTO</label><input id="bValue" type="number" min="0" value="${data.budget}"></div><button type="button" class="primary full" onclick="saveBudget()">Guardar</button>`)}
function openReminder(){modal(`<h2>Nuevo recordatorio 🔔</h2><div class="field"><label>RECORDATORIO</label><input id="rTitle" placeholder="Ej. Comprar agua"></div><div class="field"><label>NOTA</label><input id="rNotes" placeholder="Opcional"></div><div class="field"><label>FECHA</label><input id="rDate" type="date"></div><div class="field"><label>HORA</label><input id="rTime" type="time"></div><button type="button" class="primary full" onclick="saveReminder()">Guardar recordatorio</button>`)}
async function saveReminder(){if(!db)return toast('Supabase no está disponible');const title=$('#rTitle').value.trim();if(!title)return toast('Escribe un recordatorio');const r=await db.from('reminders').insert({title,notes:$('#rNotes').value.trim()||null,reminder_date:$('#rDate').value||null,reminder_time:$('#rTime').value||null}).select().single();if(r.error)return toast(r.error.message);data.reminders.push(r.data);renderReminders();closeModal();toast('Recordatorio guardado 🌸')};window.saveReminder=saveReminder;
async function toggleReminder(id,completed){if(!db)return;const r=await db.from('reminders').update({completed}).eq('id',id);if(r.error)return toast(r.error.message);const x=data.reminders.find(x=>x.id===id);if(x)x.completed=completed;renderReminders()};window.toggleReminder=toggleReminder;
function combos(){const have=new Set(data.home.map(x=>x.name.toLowerCase().trim()));const matches=data.recipes.map(r=>({...r,n:(r.recipe_ingredients||[]).filter(i=>!have.has(i.ingredient_name.toLowerCase().trim())).length})).sort((a,b)=>a.n-b.n).slice(0,6);const e=$('#combo');if(!e)return;e.innerHTML=matches.map(r=>`<article><h3>${esc(r.name)}</h3><p>${r.n===0?'✨ Puedes prepararlo con lo que tienes.':'Te faltan '+r.n+' ingrediente(s).'}</p></article>`).join('')||'<div class="empty">Carga recetas para ver combinaciones.</div>'}
document.addEventListener('DOMContentLoaded',()=>{if($('#addBuy'))$('#addBuy').onclick=openBuy;if($('#addHome'))$('#addHome').onclick=openHome;if($('#editBudget'))$('#editBudget').onclick=openBudget;if($('#combos'))$('#combos').onclick=combos;if($('#addReminder'))$('#addReminder').onclick=openReminder;const m=$('#modal');if(m)m.addEventListener('click',e=>{if(e.target===m)closeModal()});init()});