(function(){
  const URL='https://evmqqjtglapwnezbttds.supabase.co';
  const KEY='sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w';
  let authClient=null;
  const $=s=>document.querySelector(s);
  function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
  function ensureStyles(){if($('#authStyles'))return;const s=document.createElement('style');s.id='authStyles';s.textContent=`#authGate{position:fixed;inset:0;background:#fff5f8;z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px}#authGate.hidden{display:none}.auth-card{width:min(420px,100%);background:#fff;border:1px solid #f0dfe5;border-radius:28px;padding:34px;box-shadow:0 20px 60px #7e405a12;text-align:center}.auth-flower{width:70px;height:70px;margin:0 auto 18px;border-radius:22px;background:#f7c8d8;display:grid;place-items:center;font-size:38px}.auth-card h1{margin:0;color:#513c46}.auth-card p{color:#987a85;line-height:1.6}.auth-field{text-align:left;margin:14px 0}.auth-field label{display:block;font-size:11px;letter-spacing:1.4px;color:#c47792;font-weight:bold;margin-bottom:6px}.auth-field input{width:100%;padding:13px;border:1px solid #ecdbe2;border-radius:12px;outline:none}.auth-actions button{width:100%;padding:13px;border-radius:13px;margin-top:8px}.auth-primary{background:#df8fac;color:#fff;border:0}.auth-secondary{background:#fff;color:#bd718c;border:1px solid #edc8d5}.auth-error{color:#c85f7b;background:#fff0f5;padding:10px;border-radius:10px;font-size:13px;display:none;margin-top:12px}.auth-note{font-size:12px!important}`;document.head.appendChild(s)}
  function gate(){let g=$('#authGate');if(!g){g=document.createElement('div');g.id='authGate';document.body.appendChild(g)}g.className='';g.innerHTML=`<div class="auth-card"><div class="auth-flower">🌸</div><h1>Organización</h1><p>Tu espacio personal para organizar tu hogar.</p><form id="authForm"><div class="auth-field"><label>CORREO</label><input id="authEmail" type="email" autocomplete="email" required placeholder="Tu correo"></div><div class="auth-field"><label>CONTRASEÑA</label><input id="authPassword" type="password" autocomplete="current-password" required minlength="6" placeholder="Tu contraseña"></div><div class="auth-actions"><button class="auth-primary" type="submit">Entrar 🌸</button><button class="auth-secondary" id="authSignup" type="button">Crear mi acceso</button></div><div id="authError" class="auth-error"></div></form><p class="auth-note">La contraseña se gestiona de forma segura con Supabase Auth.</p></div>`;
    $('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;setErr('');const r=await authClient.auth.signInWithPassword({email,password});if(r.error)setErr(r.error.message)};
    $('#authSignup').onclick=async()=>{const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<6)return setErr('Escribe tu correo y una contraseña de al menos 6 caracteres.');const r=await authClient.auth.signUp({email,password});if(r.error)return setErr(r.error.message);setErr('Acceso creado. Si Supabase solicita confirmar tu correo, revisa tu email y luego entra.');};
  }
  function setErr(t){const e=$('#authError');if(!e)return;e.textContent=t;e.style.display=t?'block':'none'}
  function showApp(){const g=$('#authGate');if(g)g.classList.add('hidden');document.body.classList.remove('locked')}
  function showLogin(){gate();const g=$('#authGate');if(g)g.classList.remove('hidden')}
  async function init(){ensureStyles();if(!window.supabase?.createClient)return;authClient=window.supabase.createClient(URL,KEY);const {data}=await authClient.auth.getSession();if(data.session)showApp();else showLogin();authClient.auth.onAuthStateChange((_event,session)=>{if(session)showApp();else showLogin()});window.orgSignOut=async()=>{await authClient.auth.signOut()};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();