/* Organización - correcciones integrales v2 */
(function(){
  const URL='https://evmqqjtglapwnezbttds.supabase.co';
  const KEY='sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w';
  let client=null, recipes=[], pantry=[], meals=[];
  const cats=[['frutas','🍎 Frutas'],['verduras','🥦 Verduras'],['carnes','🥩 Carnes'],['lacteos','🥛 Lácteos'],['almacen','🥫 Almacén'],['congelados','🧊 Congelados'],['bebidas','🥤 Bebidas'],['limpieza','🧹 Limpieza'],['higiene','🧴 Higiene'],['otros','📦 Otros']];
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n)||0);
  const toast=t=>window.toast?window.toast(t):null;
  function modal(h){window.modal?h&&window.modal(h):(()=>{const b=document.querySelector('#modalBody'),m=document.querySelector('#modal');if(b&&m){b.innerHTML=h;m.classList.add('show')}})()}
  function close(){window.closeModal?window.closeModal():document.querySelector('#modal')?.classList.remove('show')}
  async function init(){if(window.supabase?.createClient)client=window.supabase.createClient(URL,KEY);if(!client)return;await Promise.all([loadRecipes(),loadPantry(),loadMeals()]);installHandlers();renderRecipes('desayuno');renderMeals()}
  async function loadRecipes(){const r=await client.from('recipes').select('*,recipe_ingredients(*)').order('created_at');if(!r.error)recipes=r.data||[]}
  async function loadPantry(){const r=await client.from('home_ingredients').select('*').order('created_at',{ascending:false});if(!r.error)pantry=r.data||[]}
  async function loadMeals(){const r=await client.from('meal_log').select('*').order('meal_date',{ascending:false}).order('meal_type');if(!r.error)meals=r.data||[]}
  function installHandlers(){
    document.addEventListener('click',e=>{const b=e.target.closest('#addMealLog');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openMeal()},{capture:true});
    document.addEventListener('click',e=>{const b=e.target.closest('#addBuy');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openBuy()},{capture:true});
    document.addEventListener('click',e=>{const b=e.target.closest('.tabs button[data-cat]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();renderRecipes(b.dataset.cat)},{capture:true});
    document.addEventListener('click',e=>{const b=e.target.closest('[data-meal-person]');if(!b)return;e.preventDefault();e.stopPropagation();renderMeals(b.dataset.mealPerson)},{capture:true});
    document.addEventListener('click',e=>{const b=e.target.closest('#addExpense');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openExpense()},{capture:true});
    document.addEventListener('click',e=>{const b=e.target.closest('[data-screen="recetas"]');if(!b)return;setTimeout(()=>renderRecipes(window.currentCategory||'desayuno'),50)});
  }
  function renderRecipes(cat){const wrap=document.querySelector('#recipes');if(!wrap)return;document.querySelectorAll('.tabs button[data-cat]').forEach(b=>b.classList.toggle('active',b.dataset.cat===cat));const have=new Set(pantry.map(x=>String(x.name||'').trim().toLowerCase()));const list=recipes.filter(r=>String(r.category||'').toLowerCase()===String(cat).toLowerCase());wrap.innerHTML=list.length?list.map(r=>{const ing=r.recipe_ingredients||[],missing=ing.filter(i=>!have.has(String(i.ingredient_name||'').trim().toLowerCase())),owned=ing.filter(i=>have.has(String(i.ingredient_name||'').trim().toLowerCase()));return `<article><h3>🍽️ ${esc(r.name)}</h3><p><b>Ingredientes</b></p><ul>${ing.map(i=>`<li>${esc(i.ingredient_name)}${i.quantity?' · '+esc(i.quantity):''}</li>`).join('')}</ul><p><b>Preparación</b><br>${esc(r.preparation||'Preparar según los ingredientes indicados.')}</p><p><b>Los tienes:</b> ${owned.map(i=>esc(i.ingredient_name)).join(', ')||'ninguno'}</p><p class="missing"><b>Te faltan:</b> ${missing.map(i=>esc(i.ingredient_name)).join(', ')||'¡Nada! 🎉'}</p><button class="secondary" type="button" onclick="window.orgPlanRecipe('${String(r.id)}')">📅 Agregar al plan</button></article>`}).join(''):'<div class="empty">Aún no hay recetas en esta categoría.</div>';window.currentCategory=cat}
  window.orgPlanRecipe=function(id){const r=recipes.find(x=>String(x.id)===String(id));if(!r)return;const t=String(r.category||'').toLowerCase();if(window.chooseMeal)window.chooseMeal(1,t)};
  function openBuy(){modal(`<h2>Agregar a compras 🛒</h2><div class="field"><label>PRODUCTO</label><input id="fxName" placeholder="Ej. banana"></div><div class="field"><label>CATEGORÍA</label><select id="fxCat">${cats.map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}</select></div><div class="field"><label>CANTIDAD</label><input id="fxQty" placeholder="Ej. 1 kg"></div><div class="field"><label>PRECIO ESTIMADO</label><input id="fxPrice" type="number" min="0" placeholder="0"></div><button class="primary full" type="button" onclick="window.orgSaveBuy()">Guardar</button>`)}
  window.orgSaveBuy=async function(){const name=document.querySelector('#fxName')?.value.trim();if(!name)return toast('Escribe un producto');const row={name,category:document.querySelector('#fxCat').value,quantity:document.querySelector('#fxQty').value.trim(),estimated_price:Number(document.querySelector('#fxPrice').value)||0};let r=await client.from('shopping_items').insert(row).select().single();if(r.error&&/category/i.test(r.error.message)){delete row.category;r=await client.from('shopping_items').insert(row).select().single()}if(r.error)return toast(r.error.message);close();toast('Agregado a la lista 🛒')};
  function openMeal(){const today=new Date().toISOString().slice(0,10);modal(`<h2>Registrar comida 🍽️</h2><p>Registra lo que hiciste para ti, para Deivis o para los dos.</p><div class="field"><label>FECHA</label><input id="fxMealDate" type="date" value="${today}"></div><div class="field"><label>COMIDA</label><select id="fxMealType"><option value="desayuno">☀️ Desayuno</option><option value="almuerzo">🍝 Almuerzo</option><option value="merienda">🥪 Merienda</option><option value="cena">🌙 Cena</option></select></div><div class="field"><label>¿PARA QUIÉN?</label><select id="fxMealPerson"><option value="Marbell">🌸 Marbell</option><option value="Deivis">💙 Deivis</option><option value="Los dos">👩👨🏻 Los dos</option></select></div><div class="field"><label>¿QUÉ HICISTE?</label><input id="fxMealName" placeholder="Ej. pollo con arroz"></div><div class="field"><label>DÓNDE</label><select id="fxMealLocation"><option>Casa</option><option>Mamá</option><option>Otro</option></select></div><div class="field"><label>NOTA</label><input id="fxMealNotes" placeholder="Opcional"></div><button class="primary full" type="button" onclick="window.orgSaveMeal()">Guardar comida</button>`)}
  window.orgSaveMeal=async function(){const date=document.querySelector('#fxMealDate').value,type=document.querySelector('#fxMealType').value,person=document.querySelector('#fxMealPerson').value,name=document.querySelector('#fxMealName').value.trim(),location=document.querySelector('#fxMealLocation').value,notes=document.querySelector('#fxMealNotes').value.trim()||null;if(!name)return toast('Escribe qué comida hiciste');const people=person==='Los dos'?['Marbell','Deivis']:[person];const rows=people.map(p=>({meal_date:date,meal_type:type,person:p,meal_name:name,location,notes}));const r=await client.from('meal_log').insert(rows).select();if(r.error)return toast(r.error.message);meals.unshift(...(r.data||[]));close();renderMeals();toast(person==='Los dos'?'Comida guardada para los dos 👩👨🏻':'Comida guardada 🍽️')};
  function renderMeals(filter='todos'){const e=document.querySelector('#mealLogList');if(!e)return;const labels={desayuno:'☀️ Desayuno',almuerzo:'🍝 Almuerzo',merienda:'🥪 Merienda',cena:'🌙 Cena'};const list=filter==='todos'?meals:filter==='Los dos'?meals.filter(x=>x.person==='Marbell'||x.person==='Deivis'):meals.filter(x=>x.person===filter);e.innerHTML=list.length?list.map(x=>`<div class="item"><div><b>${labels[x.meal_type]||x.meal_type} · ${esc(x.meal_name)}</b><small>${x.person==='Marbell'?'🌸 Marbell':'💙 Deivis'} · ${esc(x.meal_date)}${x.location?' · '+esc(x.location):''}</small></div><button class="secondary" type="button" onclick="window.orgDeleteMeal('${x.id}')">Eliminar</button></div>`).join(''):'<div class="empty">Todavía no registraste comidas. 🌸</div>';document.querySelectorAll('[data-meal-person]').forEach(b=>b.classList.toggle('active',(b.dataset.mealPerson||'todos')===filter))}
  window.orgDeleteMeal=async function(id){const r=await client.from('meal_log').delete().eq('id',id);if(r.error)return toast(r.error.message);meals=meals.filter(x=>x.id!==id);renderMeals();toast('Comida eliminada')};
  function openExpense(){modal(`<h2>Agregar gasto 💸</h2><div class="tabs"><button class="active" type="button" onclick="window.orgExpenseForm('service')">🏠 Servicio</button><button type="button" onclick="window.orgExpenseForm('personal')">🌸 Personal</button></div><div id="fxExpenseForm"></div>`);window.orgExpenseForm('service')}
  window.orgExpenseForm=function(type){const e=document.querySelector('#fxExpenseForm');if(!e)return;e.innerHTML=type==='service'?`<div class="field"><label>SERVICIO</label><select id="fxService">${['Luz','Agua','Gas','Internet','ABL','DirecTV'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>IMPORTE</label><input id="fxServiceAmount" type="number" min="0"></div><div class="field"><label>DÍA DE VENCIMIENTO</label><input id="fxServiceDue" type="number" min="1" max="31"></div><div class="field"><label>NOTA</label><input id="fxServiceNote"></div><button class="primary full" type="button" onclick="window.orgSaveService()">Guardar servicio</button>`:`<div class="field"><label>GASTO PERSONAL</label><input id="fxPersonalName" placeholder="Ej. ropa, peluquería, salida..."></div><div class="field"><label>IMPORTE</label><input id="fxPersonalAmount" type="number" min="0"></div><div class="field"><label>FECHA</label><input id="fxPersonalDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>NOTA</label><input id="fxPersonalNote"></div><button class="primary full" type="button" onclick="window.orgSavePersonal()">Guardar gasto</button>`};
  window.orgSaveService=async function(){const month=new Date().toISOString().slice(0,7)+'-01';const r=await client.from('services').insert({name:document.querySelector('#fxService').value,amount:Number(document.querySelector('#fxServiceAmount').value)||0,due_day:Number(document.querySelector('#fxServiceDue').value)||null,month,notes:document.querySelector('#fxServiceNote').value.trim()||null});if(r.error)return toast(r.error.message);close();toast('Servicio guardado 🏠')};
  window.orgSavePersonal=async function(){const name=document.querySelector('#fxPersonalName').value.trim();if(!name)return toast('Escribe el gasto');const r=await client.from('expenses').insert({name,category:'personal',amount:Number(document.querySelector('#fxPersonalAmount').value)||0,expense_date:document.querySelector('#fxPersonalDate').value,notes:document.querySelector('#fxPersonalNote').value.trim()||null});if(r.error)return toast(r.error.message);close();toast('Gasto personal guardado 🌸')};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();