(function(){
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  function navigate(target){const e=$('#'+target);if(!e)return;$$('.screen').forEach(x=>x.classList.remove('active'));e.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(window.innerWidth<=900&&$('#nav'))$('#nav').style.display='none';if(target==='recetas')window.currentCategory=window.currentCategory||'desayuno';}
  function addBackArrow(sectionId){
    const section=$('#'+sectionId); if(!section || sectionId==='casa') return;
    const head=section.querySelector('.head'); if(!head || head.querySelector('.casa-back-arrow')) return;
    const b=document.createElement('button');
    b.className='secondary casa-back-arrow'; b.type='button'; b.textContent='🔙';
    b.setAttribute('aria-label','Volver a Mi casa'); b.title='Volver a Mi casa';
    b.onclick=()=>navigate('casa');
    head.insertBefore(b,head.firstChild);
  }
  function showDespensa(){
    const casa=$('#casa'),hub=$('#casaHub');if(!casa)return;
    if(hub)hub.style.display='none';
    const head=casa.querySelector('.head'),panel=casa.querySelector('.panel');
    if(head)head.style.display='';if(panel)panel.style.display='';
    if(!$('#backCasaHub')){const b=document.createElement('button');b.id='backCasaHub';b.className='secondary casa-back-arrow';b.type='button';b.textContent='🔙';b.setAttribute('aria-label','Volver a Mi casa');b.title='Volver a Mi casa';b.onclick=()=>{if(head)head.style.display='none';if(panel)panel.style.display='none';if(hub)hub.style.display='';b.remove()};head?.appendChild(b)}
  }
  function addCard(container,title,icon,desc,target){if(!container)return;const b=document.createElement('button');b.className='org-subcard';b.type='button';b.innerHTML=`<span>${icon}</span><b>${title}</b><small>${desc}</small>`;b.onclick=()=>target==='despensa'?showDespensa():(window.showScreen?.(target)||navigate(target));container.appendChild(b)}
  function reorganize(){
    const casa=$('#casa');
    if(casa&&!$('#casaHub')){
      const existingHead=casa.querySelector('.head'),existingPanel=casa.querySelector('.panel');
      if(existingHead)existingHead.style.display='none';if(existingPanel)existingPanel.style.display='none';
      const hub=document.createElement('div');hub.id='casaHub';hub.className='org-hub';hub.innerHTML='<h2>Todo lo de tu casa, en un solo lugar 🌸</h2><p>Elige qué quieres organizar.</p><div class="org-grid"></div>';
      casa.insertBefore(hub,casa.firstChild);
      const grid=hub.querySelector('.org-grid');
      addCard(grid,'Despensa','🥫','Lo que tienes en casa','despensa');
      addCard(grid,'Comidas','🍽️','Lo que hicieron Marbell y Deivis','comidas');
      addCard(grid,'¿Qué cocino?','✨','Ideas según tus ingredientes','cocinar');
      addCard(grid,'Recetas','📖','Desayunos, almuerzos, meriendas, cenas y jugos','recetas');
    }
    const nav=$('#nav');['recetas','comidas','cocinar','gastos'].forEach(id=>nav?.querySelector(`[data-screen="${id}"]`)?.remove());
    ['recetas','comidas','cocinar'].forEach(addBackArrow);
    const presupuesto=$('#presupuesto');if(presupuesto&&!$('#goGastos')){const b=document.createElement('button');b.id='goGastos';b.className='secondary';b.type='button';b.textContent='💸 Ver gastos';b.onclick=()=>window.showScreen?.('gastos')||navigate('gastos');presupuesto.querySelector('.head')?.appendChild(b);}
    const gastos=$('#gastos');if(gastos&&!$('#gastosBack')){const b=document.createElement('button');b.id='gastosBack';b.className='secondary';b.type='button';b.textContent='🔙';b.setAttribute('aria-label','Volver a presupuesto');b.title='Volver a presupuesto';b.onclick=()=>window.showScreen?.('presupuesto')||navigate('presupuesto');gastos.querySelector('.head')?.appendChild(b)}
    const semana=$('#planificador');if(semana&&!$('#monthMeals')){const box=document.createElement('div');box.id='monthMeals';box.className='panel org-month';box.innerHTML='<div class="org-month-head"><div><h2>🍽️ Lo que hemos comido</h2><p>Consulta el historial de comidas de Marbell y Deivis durante el mes.</p></div><div class="month-controls"><button id="prevMonth" type="button">‹</button><b id="monthLabel"></b><button id="nextMonth" type="button">›</button></div></div><div id="monthMealList"></div>';semana.appendChild(box);$('#prevMonth').onclick=()=>changeMonth(-1);$('#nextMonth').onclick=()=>changeMonth(1);loadMonthMeals();}
    setupReminders();
  }
  let monthCursor=new Date();monthCursor.setDate(1);
  function changeMonth(n){monthCursor.setMonth(monthCursor.getMonth()+n);loadMonthMeals()}
  async function loadMonthMeals(){const list=$('#monthMealList'),label=$('#monthLabel');if(!list)return;const db=window.supabase?.createClient?.('https://evmqqjtglapwnezbttds.supabase.co','sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w');if(!db){list.innerHTML='<div class="empty">No se pudo conectar.</div>';return}const y=monthCursor.getFullYear(),m=String(monthCursor.getMonth()+1).padStart(2,'0'),start=`${y}-${m}-01`,end=new Date(y,monthCursor.getMonth()+1,1).toISOString().slice(0,10);label.textContent=monthCursor.toLocaleDateString('es-AR',{month:'long',year:'numeric'});const r=await db.from('meal_log').select('*').gte('meal_date',start).lt('meal_date',end).order('meal_date',{ascending:false}).order('meal_type');if(r.error){list.innerHTML='<div class="empty">No pudimos cargar el historial.</div>';return}const labels={desayuno:'☀️ Desayuno',almuerzo:'🍝 Almuerzo',merienda:'🥪 Merienda',cena:'🌙 Cena'};const rows=r.data||[];const grouped={};rows.forEach(x=>(grouped[x.meal_date]??=[]).push(x));list.innerHTML=rows.length?Object.entries(grouped).map(([date,items])=>`<div class="month-day"><h3>${new Date(date+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'})}</h3>${items.map(x=>`<div class="month-meal"><b>${labels[x.meal_type]||x.meal_type}</b><span>${x.person==='Marbell'?'🌸 Marbell':x.person==='Deivis'?'💙 Deivis':'👩👨🏻 Los dos'} · ${esc2(x.meal_name)}</span>${x.location?`<small>📍 ${esc2(x.location)}</small>`:''}</div>`).join('')}</div>`).join(''):'<div class="empty">Todavía no registraron comidas este mes. 🌸</div>'}
  function esc2(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
  async function setupReminders(){const section=$('#recordatorios');if(!section||$('#reminderTabs'))return;const head=section.querySelector('.head');const oldButton=$('#addReminder');if(oldButton)oldButton.remove();const actions=document.createElement('div');actions.className='reminder-actions';actions.innerHTML='<button class="primary" id="addTask">＋ Tarea</button><button class="secondary" id="addReminderNew">＋ Recordatorio</button>';head?.appendChild(actions);const panel=section.querySelector('.panel');if(!panel)return;panel.innerHTML='<div class="tabs" id="reminderTabs"><button class="active" data-rview="tasks">🏠 Tareas</button><button data-rview="reminders">🔔 Recordatorios</button></div><div id="reminderContent"></div>';$$('[data-rview]').forEach(b=>b.onclick=()=>{$$("[data-rview]").forEach(x=>x.classList.remove('active'));b.classList.add('active');renderReminderView(b.dataset.rview)});$('#addTask').onclick=()=>openTask();$('#addReminderNew').onclick=()=>window.openReminder?.()||document.querySelector('#addReminder')?.click();renderReminderView('tasks')}
  async function fetchReminders(){const db=window.supabase?.createClient?.('https://evmqqjtglapwnezbttds.supabase.co','sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w');if(!db)return[];const r=await db.from('reminders').select('*').order('completed').order('reminder_date',{ascending:true});return r.error?[]:(r.data||[])}
  async function renderReminderView(view){const e=$('#reminderContent');if(!e)return;const rows=await fetchReminders();const tasks=rows.filter(x=>String(x.notes||'').startsWith('[TAREA]'));const normal=rows.filter(x=>!String(x.notes||'').startsWith('[TAREA]'));const list=view==='tasks'?tasks:normal;e.innerHTML=list.length?list.map(x=>{const notes=String(x.notes||'').replace(/^\[TAREA\]\s*/,'');return `<div class="item"><div><b>${x.completed?'✓ ':''}${esc2(x.title)}</b><small>${esc2(notes)}${x.reminder_date?' · '+esc2(x.reminder_date):''}${x.reminder_time?' · '+esc2(x.reminder_time.slice(0,5)):''}</small></div><button type="button" onclick="window.orgToggleTask('${x.id}',${!x.completed})">${x.completed?'↩ Pendiente':'✓ Hecho'}</button></div>`}).join(''):'<div class="empty">'+(view==='tasks'?'No tienes tareas pendientes. 🌸':'No tienes recordatorios. 🌸')+'</div>'}
  function openTask(){const today=new Date().toISOString().slice(0,10);if(!window.modal)return;window.modal(`<h2>Nueva tarea 🏠</h2><div class="field"><label>¿QUÉ TIENES QUE HACER?</label><input id="taskTitle" placeholder="Ej. Lavar los paños"></div><div class="field"><label>FECHA</label><input id="taskDate" type="date" value="${today}"></div><div class="field"><label>HORA</label><input id="taskTime" type="time"></div><div class="field"><label>NOTA</label><input id="taskNote" placeholder="Opcional"></div><button class="primary full" type="button" onclick="window.orgSaveTask()">Guardar tarea</button>`)}
  window.orgSaveTask=async function(){const db=window.supabase?.createClient?.('https://evmqqjtglapwnezbttds.supabase.co','sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w');const title=$('#taskTitle')?.value.trim();if(!db||!title)return window.toast?.('Escribe la tarea');const note=$('#taskNote')?.value.trim();const r=await db.from('reminders').insert({title,notes:'[TAREA] '+(note||''),reminder_date:$('#taskDate')?.value||null,reminder_time:$('#taskTime')?.value||null}).select().single();if(r.error)return window.toast?.(r.error.message);window.closeModal?.();renderReminderView('tasks');window.toast?.('Tarea guardada 🌸')}
  window.orgToggleTask=async function(id,completed){const db=window.supabase?.createClient?.('https://evmqqjtglapwnezbttds.supabase.co','sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w');if(!db)return;const r=await db.from('reminders').update({completed}).eq('id',id);if(r.error)return window.toast?.(r.error.message);renderReminderView('tasks');}
  function style(){if($('#orgV2Styles'))return;const s=document.createElement('style');s.id='orgV2Styles';s.textContent=`.org-hub{background:#fff;border:1px solid #f0dfe5;border-radius:24px;padding:25px;margin:22px 0}.org-hub h2{margin:0 0 6px}.org-hub p{color:#987a85}.org-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:18px}.org-subcard{background:#fff5f8;border:1px solid #f0dfe5;border-radius:18px;padding:20px;text-align:left;color:#513c46}.org-subcard span{display:block;font-size:30px;margin-bottom:10px}.org-subcard b,.org-subcard small{display:block}.org-subcard small{color:#987a85;margin-top:5px;line-height:1.4}.casa-back-arrow{min-width:44px;width:44px;height:44px;padding:0;font-size:22px;display:inline-flex;align-items:center;justify-content:center;margin-bottom:12px}.org-month{margin-top:25px}.org-month-head{display:flex;justify-content:space-between;align-items:center;gap:15px}.org-month-head h2{margin:0}.org-month-head p{color:#987a85}.month-controls{display:flex;align-items:center;gap:10px}.month-controls button{width:36px;height:36px;border-radius:10px;background:#fff0f5;color:#b96782}.month-day{padding:15px 0;border-bottom:1px solid #f5e8ed}.month-day h3{color:#c47792;text-transform:capitalize;margin:0 0 10px}.month-meal{display:grid;grid-template-columns:150px 1fr auto;gap:10px;padding:9px 0;color:#6d5360}.month-meal small{color:#9b7c87}.reminder-actions{display:flex;gap:8px;flex-wrap:wrap}.reminder-actions button{margin:8px 0}.tabs button.active{background:#df8fac!important;color:#fff!important}@media(max-width:900px){.org-grid{grid-template-columns:1fr 1fr}.month-meal{grid-template-columns:1fr}}@media(max-width:600px){.org-grid{grid-template-columns:1fr}.org-month-head{display:block}.month-controls{margin-top:12px}.reminder-actions{margin-top:12px}}`;document.head.appendChild(s)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{style();reorganize();setTimeout(reorganize,500)});else{style();reorganize();setTimeout(reorganize,500)}
})();