(function(){
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  function addCard(container,title,icon,desc,target){if(!container)return;const b=document.createElement('button');b.className='org-subcard';b.type='button';b.innerHTML=`<span>${icon}</span><b>${title}</b><small>${desc}</small>`;b.onclick=()=>window.showScreen?.(target)||document.querySelector(`[data-screen="${target}"]`)?.click();container.appendChild(b)}
  function reorganize(){
    const casa=$('#casa');
    if(casa&&!$('#casaHub')){const hub=document.createElement('div');hub.id='casaHub';hub.className='org-hub';hub.innerHTML='<h2>Todo lo de tu casa, en un solo lugar 🌸</h2><p>Elige qué quieres organizar.</p><div class="org-grid"></div>';casa.querySelector('.cards')?.before(hub);const grid=hub.querySelector('.org-grid');addCard(grid,'Despensa','🥫','Lo que tienes en casa','casa');addCard(grid,'Comidas','🍽️','Lo que hicieron Marbell y Deivis','comidas');addCard(grid,'¿Qué cocino?','✨','Ideas según tus ingredientes','cocinar');addCard(grid,'Recetas','📖','Desayunos, almuerzos, meriendas, cenas y jugos','recetas');}
    const nav=$('#nav');['recetas','comidas','cocinar','gastos'].forEach(id=>nav?.querySelector(`[data-screen="${id}"]`)?.remove());
    const presupuesto=$('#presupuesto');if(presupuesto&&!$('#goGastos')){const b=document.createElement('button');b.id='goGastos';b.className='secondary';b.type='button';b.textContent='💸 Ver gastos';b.onclick=()=>document.querySelector('[data-screen="gastos"]')?.click();presupuesto.querySelector('.head')?.appendChild(b);}
    const gastos=$('#gastos');if(gastos&&!$('#gastosBack')){const b=document.createElement('button');b.id='gastosBack';b.className='secondary';b.type='button';b.textContent='← Volver a presupuesto';b.onclick=()=>document.querySelector('[data-screen="presupuesto"]')?.click();gastos.querySelector('.head')?.appendChild(b)}
    const semana=$('#planificador');if(semana&&!$('#monthMeals')){const box=document.createElement('div');box.id='monthMeals';box.className='panel org-month';box.innerHTML='<div class="org-month-head"><div><h2>🍽️ Lo que hemos comido</h2><p>Consulta el historial de comidas de Marbell y Deivis durante el mes.</p></div><div class="month-controls"><button id="prevMonth" type="button">‹</button><b id="monthLabel"></b><button id="nextMonth" type="button">›</button></div></div><div id="monthMealList"></div>';semana.appendChild(box);$('#prevMonth').onclick=()=>changeMonth(-1);$('#nextMonth').onclick=()=>changeMonth(1);loadMonthMeals();}
  }
  let monthCursor=new Date();monthCursor.setDate(1);
  function changeMonth(n){monthCursor.setMonth(monthCursor.getMonth()+n);loadMonthMeals()}
  async function loadMonthMeals(){const list=$('#monthMealList'),label=$('#monthLabel');if(!list)return;const db=window.supabase?.createClient?.('https://evmqqjtglapwnezbttds.supabase.co','sb_publishable_bri9jNvVFIyaynVhOHvBGA_9u4u527w');if(!db){list.innerHTML='<div class="empty">No se pudo conectar.</div>';return}const y=monthCursor.getFullYear(),m=String(monthCursor.getMonth()+1).padStart(2,'0'),start=`${y}-${m}-01`,end=new Date(y,monthCursor.getMonth()+1,1).toISOString().slice(0,10);label.textContent=monthCursor.toLocaleDateString('es-AR',{month:'long',year:'numeric'});const r=await db.from('meal_log').select('*').gte('meal_date',start).lt('meal_date',end).order('meal_date',{ascending:false}).order('meal_type');if(r.error){list.innerHTML='<div class="empty">No pudimos cargar el historial.</div>';return}const labels={desayuno:'☀️ Desayuno',almuerzo:'🍝 Almuerzo',merienda:'🥪 Merienda',cena:'🌙 Cena'};const rows=r.data||[];const grouped={};rows.forEach(x=>(grouped[x.meal_date]??=[]).push(x));list.innerHTML=rows.length?Object.entries(grouped).map(([date,items])=>`<div class="month-day"><h3>${new Date(date+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'})}</h3>${items.map(x=>`<div class="month-meal"><b>${labels[x.meal_type]||x.meal_type}</b><span>${x.person==='Marbell'?'🌸 Marbell':x.person==='Deivis'?'💙 Deivis':'👩👨🏻 Los dos'} · ${esc2(x.meal_name)}</span>${x.location?`<small>📍 ${esc2(x.location)}</small>`:''}</div>`).join('')}</div>`).join(''):'<div class="empty">Todavía no registraron comidas este mes. 🌸</div>'}
  function esc2(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
  function patchHome(){const old=window.show;window.showScreen=window.showScreen||old;}
  function style(){if($('#orgV2Styles'))return;const s=document.createElement('style');s.id='orgV2Styles';s.textContent=`.org-hub{background:#fff;border:1px solid #f0dfe5;border-radius:24px;padding:25px;margin:22px 0}.org-hub h2{margin:0 0 6px}.org-hub p{color:#987a85}.org-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:18px}.org-subcard{background:#fff5f8;border:1px solid #f0dfe5;border-radius:18px;padding:20px;text-align:left;color:#513c46}.org-subcard span{display:block;font-size:30px;margin-bottom:10px}.org-subcard b,.org-subcard small{display:block}.org-subcard small{color:#987a85;margin-top:5px;line-height:1.4}.org-month{margin-top:25px}.org-month-head{display:flex;justify-content:space-between;align-items:center;gap:15px}.org-month-head h2{margin:0}.org-month-head p{color:#987a85}.month-controls{display:flex;align-items:center;gap:10px}.month-controls button{width:36px;height:36px;border-radius:10px;background:#fff0f5;color:#b96782}.month-day{padding:15px 0;border-bottom:1px solid #f5e8ed}.month-day h3{color:#c47792;text-transform:capitalize;margin:0 0 10px}.month-meal{display:grid;grid-template-columns:150px 1fr auto;gap:10px;padding:9px 0;color:#6d5360}.month-meal small{color:#9b7c87}@media(max-width:900px){.org-grid{grid-template-columns:1fr 1fr}.month-meal{grid-template-columns:1fr}}@media(max-width:600px){.org-grid{grid-template-columns:1fr}.org-month-head{display:block}.month-controls{margin-top:12px}}`;document.head.appendChild(s)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{style();reorganize();setTimeout(reorganize,500)});else{style();reorganize();setTimeout(reorganize,500)}
})();